apiVersion: v1
kind: Pod
metadata:
  name: user-service
spec:
  containers:
    - name: mysql
      image: mysql:5.7
      ports:
        - containerPort: 3306
      env:
        - name: MYSQL_ROOT_PASSWD
          value: root123!
    - name: user-service
      image: stevenzearo/user-service:0.0.1
      ports:
        - containerPort: 8401
    - name: registry-site
      image: stevenzearo/registry-site:0.0.1
      ports:
        - containerPort: 8400
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: mysql-service
  ports:
    - port: 8401
      targetPort: 8401
      protocol: TCP
      nodePort: 30002
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: registry-site
spec:
  selector:
    app: registry-site
  ports:
    - port: 8400
      targetPort: 8400
      protocol: TCP
      nodePort: 30001
  type: NodePort
