apiVersion: v1
kind: ReplicationController
metadata:
  name: registry-site
spec:
  replicas: 1
  selector:
    app: registry-site
  template:
    metadata:
      labels:
        app: registry-site
    spec:
      containers:
      - name: registry-site
        image: stevenzearo/registry-site:latest
        ports:
        - containerPort: 8400
